language: crystal
os: linux
dist: trusty
before_install:
  - sudo apt-get purge couchdb
  - echo "deb https://apache.bintray.com/couchdb-deb trusty main" | sudo tee -a /etc/apt/sources.list
  - curl -L https://couchdb.apache.org/repo/bintray-pubkey.asc | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq couchdb
  - sudo service couchdb start
